### ISSUE TITLE
Torch GPU Test - `tf_draw_seed` casting error

### ISSUE THREAD

**Issue by sampathweb** [keras-team/keras-core#587]
`RandomFlip` was made backend agnostic in PR: #515 and might have exposed an issue of [tf_draw_seed](
https://github.com/keras-team/keras-core/blob/main/keras_core/backend/tensorflow/random.py#L12).  But if we try to convert to numpy via `backend.convert_to_numpy(..)`, it causes errors in other tests, when there are symbolic TF Tensors.  How should we address it?

```
E               File "keras_core/layers/preprocessing/random_flip.py", line 63, in random_flipped_inputs  *
E                   flipped_outputs = self.backend.cond(
E               File "keras_core/backend/tensorflow/random.py", line 25, in uniform  *
E                   seed = tf_draw_seed(seed)
E               File "keras_core/backend/tensorflow/random.py", line 12, in tf_draw_seed  *
E                   return tf.cast(draw_seed(seed), dtype="int32")
E               File "miniconda3/envs/keras-gpu/lib/python3.10/site-packages/torch/_tensor.py", line 970, in __array__
E                   return self.numpy()
E
E               TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

../../miniconda3/envs/keras-gpu/lib/python3.10/site-packages/torch/_tensor.py:970: TypeError
```

**Comment by fchollet** [comment]
This looks like the TF random ops trying to draw a seed from a torch SeedGenerator. The bug is that this should never happen in the first place -- TF random ops should use a TF SeedGenerator.

This is because the layer used `seed_generator = self._get_seed_generator()` instead of `seed_generator = self._get_seed_generator(self.backend._backend)`. Let me fix this quick

**Comment by fchollet** [comment]
Done
