### ISSUE TITLE
LBFGS Optimizer

### ISSUE THREAD

**Issue by kamil2oster** [keras-team/keras-core#744]
Hi,
I wondered whether you thought about incorporating LBFGS optimizer into keras-core?
I would normally specify optimizer in model.compile(optimizer=...).

Thanks!

**Comment by fchollet** [comment]
Thanks for the suggestion. LBFGS has never been included in the Keras API, mostly because it is a batch optimization method (as opposed to a mini-batch method, which is what Keras `fit()` supports) and because it has not been shown to be a good fit for neural networks in general (which universally use SGD variants).

You can however implement LBFGS manually using Keras Core `keras.ops` APIs, for use in a custom batch training loop.
