### ISSUE TITLE
With keras-nlp: "Could not interpret optimizer identifier"

### ISSUE THREAD

**Issue by bermeitinger-b** [keras-team/keras-core#760]
I'm trying the tutorial here: https://keras.io/examples/generative/gpt2_text_generation_with_kerasnlp
Shortened to the important part (and changed backend to tensorflow) is here: https://colab.research.google.com/drive/1HJVaWartvwI8pNbKZY2SxpUWr8N3l7bp?usp=sharing

The code is here:
```python
import keras_nlp
import tensorflow as tf
import keras_core as keras
import tensorflow_datasets as tfds

print(f"keras-core: {keras.__version__}")
print(f"keras-nlp:  {keras_nlp.__version__}")
print(f"tensorflow: {tf.__version__}")

tf.random.set_seed(1)

# load data
train_ds = tfds.load("reddit_tifu", split="train", as_supervised=True).map(lambda document, _: document).batch(32)

gpt2 = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en", preprocessor=keras_nlp.models.GPT2CausalLMPreprocessor.from_preset("gpt2_base_en", sequence_length=128))

loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
gpt2.compile(
    optimizer=keras.optimizers.Adam(),
    loss=loss,
    weighted_metrics=["accuracy"],
)
gpt2.fit(train_ds, epochs=1)
```
Which failed with the backtrace:
```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-2-948e02d344f6>](https://localhost:8080/#) in <cell line: 17>()
     15 gpt2 = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en", preprocessor=keras_nlp.models.GPT2CausalLMPreprocessor.from_preset("gpt2_base_en", sequence_length=128))
     16 loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
---> 17 gpt2.compile(
     18     optimizer=keras.optimizers.Adam(),
     19     loss=loss,

3 frames

[/usr/local/lib/python3.10/dist-packages/keras/src/optimizers/__init__.py](https://localhost:8080/#) in get(identifier, **kwargs)
    317         )
    318     else:
--> 319         raise ValueError(
    320             f"Could not interpret optimizer identifier: {identifier}"
    321         )

ValueError: Could not interpret optimizer identifier: <keras_core.src.optimizers.adam.Adam object at 0x7c84d5123c40>
```

Basically, it doesn't work when putting a class as `optimizer=` instead of a string.

From the code, I don't see why it fails, the class `keras.optimizers.Adam` successfully is an instance of `keras.optimizers.Optimizer`.

This happens also in an empty (except `keras-core`, `keras-nlp`, `tensorflow-datasets` of course) virtualenv locally.

It works, when not using `keras_core`, so replacing the import with `from tensorflow import keras` makes it work.

**Comment by asingh9530** [comment]
Hi @bermeitinger-b 

Thanks for this issue. This is happening due to following.

Since from the above code gpt2 is [Task](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/task.py) Object of keras_nlp which itself  extends `PipelineModel` which itself extends `tf.keras.Model` hence it will fail as the Optimizer object you are passing is of `keras_core.optimizer.Optimizer`  but it expects `tf.keras.optimizer.Optimizer`.  

gpt2 reference [code](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/models/task.py).

`PipelineModel` reference [code](https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/utils/pipeline_model.py).


This is expected as many parts of keras_nlp is still extends `tf.keras`  and not `keras_core`.

**Comment by bermeitinger-b** [comment]
Okay, thanks for your reply From the changelogs, I interpreted it as working with `keras_core`.
