### ISSUE TITLE
Allows users to add/implement new backends

### ISSUE THREAD

**Issue by edwardyehuang** [keras-team/keras-core#807]
Hi

I read the QA on additional backend support in issue #419 and understand that the Keras-Core team currently has no plans to support new backends.

However, I would like to ask whether keras-core supports the implementation of additional backends provided by community users?

Regards

**Comment by SuryanarayanaY** [comment]
Hi @edwardyehuang ,



> I read the QA on additional backend support in issue #419 and understand that the Keras-Core team currently has no plans to support new backends.

At present keras-core supports 3 major frameworks (tensorflow,pytorch and jax) and it's not locked up forever. As mentioned in [comment-1614932813](https://github.com/keras-team/keras-core/issues/419#issuecomment-1614932813), if the target framework has a large user base or otherwise has some unique technical benefits the team is open to add the target framework as supported backend. 




> However, I would like to ask whether keras-core supports the implementation of additional backends provided by community users?

IMO, I don't think it's that straight forward. keras-core should have implementations to support those backends which is not available at this time. Tagging keras-team for more details.

**Comment by fchollet** [comment]
> However, I would like to ask whether keras-core supports the implementation of additional backends provided by community users?

You'd need to make a fork of the package in order to add a new backend. We expect this will not be a common use case. But because there is very little coupling between the Keras Core codebase and the implementation of its different backends, it would be straightforward to keep the fork in sync with the main package.
